// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP7fVKt6M3R4Pfvk7RJRqefpR9aD9uuxw',
    appId: '1:1060775617113:web:d7bd0c675b3333d6eec748',
    messagingSenderId: '1060775617113',
    projectId: 'ismtanchor',
    authDomain: 'ismtanchor.firebaseapp.com',
    storageBucket: 'ismtanchor.appspot.com',
    measurementId: 'G-N9BHS4V207',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXSF4WZ7_Y0labKj-ztaLFnB6u7aDrYxg',
    appId: '1:1060775617113:android:00147ba1e8c25421eec748',
    messagingSenderId: '1060775617113',
    projectId: 'ismtanchor',
    storageBucket: 'ismtanchor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaQM0liMugOljT-yDVgVvnyjI5zwBrU5E',
    appId: '1:1060775617113:ios:82f379ccd54a8dd6eec748',
    messagingSenderId: '1060775617113',
    projectId: 'ismtanchor',
    storageBucket: 'ismtanchor.appspot.com',
    iosBundleId: 'com.example.ismtAnchor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAP7fVKt6M3R4Pfvk7RJRqefpR9aD9uuxw",
  authDomain: "ismtanchor.firebaseapp.com",
  projectId: "ismtanchor",
  storageBucket: "ismtanchor.appspot.com",
  messagingSenderId: "1060775617113",
  appId: "1:1060775617113:web:d7bd0c675b3333d6eec748",
  measurementId: "G-N9BHS4V207"
  );

  static const FirebaseOptions windows = FirebaseOptions(
     apiKey: "AIzaSyAP7fVKt6M3R4Pfvk7RJRqefpR9aD9uuxw",
  authDomain: "ismtanchor.firebaseapp.com",
  projectId: "ismtanchor",
  storageBucket: "ismtanchor.appspot.com",
  messagingSenderId: "1060775617113",
  appId: "1:1060775617113:web:d7bd0c675b3333d6eec748",
  measurementId: "G-N9BHS4V207"
  );

}